[versions]
# libraries
annotations = "24.0.1"

kotlin = "1.9.10"
kotlin-coroutines = "1.6.4"

# plugins
changelog = "2.1.2"
detekt = "1.23.1"
dokka = "1.9.0"
gradleIntelliJPlugin = "1.15.0"
qodana = "0.1.13"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

# For build
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

[bundles]
detektplugins = ["detekt-formatting"]

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
