[versions]
# libraries
annotations = "24.0.1"
jsvg = "1.1.0"

kotlin = "1.9.10"
kotlin-coroutines = "1.6.4"
junit-jupiter = "5.10.0"
assertj = "3.24.2"

# plugins
changelog = "2.1.2"
detekt = "1.23.1"
dokka = "1.9.0"
gradleIntelliJPlugin = "1.16.0"
spotless = "6.21.0"
qodana = "0.1.13"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
jsvg = { module = "com.github.weisj:jsvg", version.ref = "jsvg" }

junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }

# For build
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

[bundles]
detektplugins = ["detekt-formatting"]
junit-jupiter = ["junit-jupiter-api", "junit-jupiter-engine"]

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
